# Generated by Django 5.2.7 on 2026-01-19 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_vote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': '3. Альбом', 'verbose_name_plural': '3. Альбомы'},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': '2. Артист / Группа', 'verbose_name_plural': '2. Артисты / Группы'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': '1. Жанр', 'verbose_name_plural': '1. Жанры'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name': '4. Песня', 'verbose_name_plural': '4. Песни'},
        ),
    ]
