# Generated by Django 5.2.7 on 2026-01-19 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_updated_at_alter_post_author_alter_post_body_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '2. Категория', 'verbose_name_plural': '2. Категории'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '1. Статья', 'verbose_name_plural': '1. Статьи'},
        ),
    ]
