# Generated by Django 5.2.7 on 2026-01-25 11:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название бренда')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': '2. Бренды и Производители',
                'verbose_name_plural': '2. Бренды и Производители',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория товара')),
                ('icon_shop_category', models.ImageField(blank=True, null=True, upload_to='shop_category_icons/', verbose_name='Иконка категории')),
            ],
            options={
                'verbose_name': '5. Категория товара',
                'verbose_name_plural': '5. Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='CurrencyRateEUR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_eur', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс')),
                ('currency_eur', models.CharField(default='BYN/EUR', max_length=10, verbose_name='Валюта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': '9. Курс BYN/EUR НБРБ',
                'verbose_name_plural': '9. Курс BYN/EUR НБРБ',
            },
        ),
        migrations.CreateModel(
            name='CurrencyRateUSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_usd', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс')),
                ('currency_usd', models.CharField(default='BYN/USD', max_length=10, verbose_name='Валюта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': '8. Курс BYN/USD НБРБ',
                'verbose_name_plural': '8. Курс BYN/USD НБРБ',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='Ед. изм.')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': '4. Единица измерения',
                'verbose_name_plural': '4. Единицы измерения',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Принято')),
                ('status', models.CharField(choices=[('pending', 'Ожидается оплата'), ('paid', 'Оплачено'), ('shipped', 'Отправлено'), ('delivered', 'Доставлено')], default='pending', max_length=10, verbose_name='Статус заказа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': '7. Заказ',
                'verbose_name_plural': '7. Заказы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/product_images/', verbose_name='Изображение')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена в USD')),
                ('price_in_byn', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Цена в BYN')),
                ('price_in_eur', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Цена в EUR')),
                ('in_stock', models.BooleanField(default=True, verbose_name='Наличие')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.brandname', verbose_name='Производитель')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': '1. Товар',
                'verbose_name_plural': '1. Товары',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='shop.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Деталь заказа',
                'verbose_name_plural': 'Детали заказа',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('selected', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'verbose_name': '6. Корзина',
                'verbose_name_plural': '6. Корзины',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Название компании')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Некорректный e-mail.')], verbose_name='Электронная почта')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^(\\+\\d{1,3}|\\d)(\\s|-|\\.)?\\d{3}(\\s|-|\\.)?\\d{3}(\\s|-|\\.)?\\d{4}$', message='Номер телефона введен некорректно.')], verbose_name='Телефон')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shop/sellers_images/logos/', verbose_name='Логотип')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': '3. Продавец',
                'verbose_name_plural': '3. Продавцы',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.seller', verbose_name='Продавец'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='shop.unit', verbose_name='Ед. изм.'),
        ),
    ]
