# Generated by Django 5.2.7 on 2026-01-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': '6. Корзина', 'verbose_name_plural': '6. Корзины'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '5. Категория товара', 'verbose_name_plural': '5. Категории товаров'},
        ),
        migrations.AlterModelOptions(
            name='currencyrateeur',
            options={'verbose_name': '9. Курс BYN/EUR НБРБ', 'verbose_name_plural': '9. Курс BYN/EUR НБРБ'},
        ),
        migrations.AlterModelOptions(
            name='currencyrateusd',
            options={'verbose_name': '8. Курс BYN/USD НБРБ', 'verbose_name_plural': '8. Курс BYN/USD НБРБ'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '7. Заказ', 'verbose_name_plural': '7. Заказы'},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': '3. Продавец', 'verbose_name_plural': '3. Продавцы'},
        ),
        migrations.AlterField(
            model_name='seller',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shop/sellers_images/logos/', verbose_name='Логотип'),
        ),
    ]
