# Generated by Django 5.2.7 on 2026-01-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_orderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидается оплата'), ('paid', 'Оплачено'), ('shipped', 'Отправлено'), ('delivered', 'Доставлено')], default='pending', max_length=10, verbose_name='Статус товара'),
        ),
    ]
