# Generated by Django 5.2.7 on 2026-01-20 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orderhistory_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидается оплата'), ('paid', 'Оплачено'), ('shipped', 'Отправлено'), ('delivered', 'Доставлено')], default='pending', max_length=10, verbose_name='Статус заказа'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая стоимость')),
                ('cart_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.cartitem', verbose_name='Корзина')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': '8. Товар в заказе',
                'verbose_name_plural': '8. Товары в заказах',
            },
        ),
        migrations.DeleteModel(
            name='OrderHistory',
        ),
    ]
