# Generated by Django 5.2.7 on 2026-01-20 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_order_items_alter_order_status_orderitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='cart_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='shop.cartitem', verbose_name='Корзина'),
        ),
    ]
