# Generated by Django 5.2.7 on 2026-01-20 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_orderitem_cart_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='cart_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.cartitem', verbose_name='Корзина'),
        ),
    ]
