# Generated by Django 5.2.7 on 2025-11-29 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_price_in_usd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_in_usd',
            new_name='price_in_byn',
        ),
    ]
