# Generated by Django 5.2.7 on 2025-11-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_price_in_usd_product_price_in_byn'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_in_eur',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
