# Generated by Django 5.2.7 on 2026-01-20 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orderdetail_delete_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='total_price',
        ),
    ]
