# Generated by Django 5.2.7 on 2026-01-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_orderdetail_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Примечания'),
        ),
    ]
