"""
Django settings for apps project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import environ
import os
from pathlib import Path
import dj_database_url
import pymysql
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('MYSQL_SECRET_KEY')
# SECRET_KEY = 'django-insecure-87j5lne(x@wvy-*6=%#t86($%t&))#aq8!e!)7qbj%%_4uv+c2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

SITE_ID = 1

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_seed',


    # Other installed applications
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # Your other apps here
    #  Settings Django Debug Toolbar (pip install django-debug-toolbar)
    'debug_toolbar',

    'whitenoise.runserver_nostatic',
    'blog',
    'music',
    'shop',
    'registration',

    'rest_framework', #Подключение DRF
    'shop_api', #Подключение нового приложения API

    'rest_framework_simplejwt',
    # опционально для blacklist:
    'rest_framework_simplejwt.token_blacklist',

]
CACHE_MIDDLEWARE_SECONDS = 3600
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # # Средства кеширования
    # 'django.middleware.cache.UpdateCacheMiddleware',
    # 'django.middleware.cache.FetchFromCacheMiddleware',

    #  Settings Django Debug Toolbar
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    # AllAuth Account middleware
    'allauth.account.middleware.AccountMiddleware',

]

ROOT_URLCONF = 'apps.urls'


#  Settings Django Debug Toolbar
INTERNAL_IPS = ['127.0.0.1', '::1']

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'apps.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # Используем MySQL-драйвер
        'NAME': os.environ.get('MYSQL_DB_NAME'),  # Имя базы данных.
        'USER': os.environ.get('MYSQL_DB_USER'),  # Пользователь MySQL
        'PASSWORD': os.environ.get('MYSQL_DB_PASSWORD'),  # Пароль пользователя
        'HOST': os.environ.get('MYSQL_DB_HOST', 'localhost'),  # Адрес сервера MySQL
        'PORT': os.environ.get('MYSQL_DB_PORT', '3306'),  # Порт MySQL (стандартный 3306)
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Префикс URL для статических файлов
# BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_URL = '/static/'

# Папка, куда будут собраны статические файлы
# STATIC_ROOT = os.path.join(BASE_DIR, 'static_collected')
STATIC_ROOT = BASE_DIR / 'static_collected'

'''1. Автоматическая регистрация статики:
   Если у вас папка static внутри каждого приложения (например, app1/static/app1, app2/static/app2 и т.д.), 
   Django автоматически соберёт статику из этих папок благодаря опции STATICFILES_FINDERS, 
   которая по умолчанию включает опцию поиска статики по каждому приложению:'''
# Поиск статических файлов
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'django.contrib.staticfiles.finders.FileSystemFinder',
]
'''2. Дополнительные пути для статики:
   Если нужно указать конкретные пути для статики, 
   вы можете дополнить STATICFILES_DIRS в settings.py:'''
STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR / 'blog/static/blog/',
    BASE_DIR / 'shop/static/shop/',
    BASE_DIR / 'music/static/music/',
    BASE_DIR / 'registration/static/registration/'
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#Регистрация
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

#Настройка зоны Минск
TIME_ZONE  = os.environ.get('TIME_ZONE')
USE_TZ = os.environ.get('USE_TZ')


#Настройка кэша MEMCACHED
# CACHES = {
#     'default': {
#         "BACKEND": "django.core.cache.backends.memcached.PyMemcacheCache",
#         "LOCATION": "127.0.0.1:11211",
#     }
# }
#Настройка кэша REDIS
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#         'LOCATION': 'redis://127.0.0.1:6379/1',
#     }
# }
# Настройка кэша DJANGO
# CACHES = {
#     'default': {
#         "BACKEND": "django.core.cache.backends.db.DatabaseCache",
#         "LOCATION": "my_cache_table",
#     }
# }

#Настройка кэша LocMem -  не подходит для Production
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
#     }
# }
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    }
}


#Настройка почтового клиента (Django settings):
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.mail.ru'
EMAIL_PORT = 465
EMAIL_USE_SSL = True

EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER  # Адрес отправителя по умолчанию
SERVER_EMAIL = EMAIL_HOST_USER        # Адрес для служебных сообщений




# #Settings for DRF and JWT  - START
# from datetime import timedelta
# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#         # можно оставить SessionAuthentication для веб-страниц, если нужно:
#         # 'rest_framework.authentication.SessionAuthentication',
#     ),
#     'DEFAULT_PERMISSION_CLASSES': (
#         'rest_framework.permissions.IsAuthenticated',  # по умолчанию защищаем все API
#     )
# }
#
# SIMPLE_JWT = {
#     'ACCESS_TOKEN_LIFETIME': timedelta(minutes=10),
#     'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
#     'ROTATE_REFRESH_TOKENS': False,   # если True — при refresh выдается новый refresh
#     'BLACKLIST_AFTER_ROTATION': True, # требует token_blacklist app
#     'ALGORITHM': 'HS256',
#     # опционально укажи SECRET_KEY, по умолчанию используется Django SECRET_KEY
# }
# #Settings for DRF and JWT  - FINISH



CSRF_COOKIE_HTTPONLY = False  # разрешаем доступ к токену через JavaScript
