"""
Django settings for apps project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import environ
import os
from pathlib import Path
import dj_database_url
import pymysql
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('MYSQL_SECRET_KEY')
# SECRET_KEY = 'django-insecure-87j5lne(x@wvy-*6=%#t86($%t&))#aq8!e!)7qbj%%_4uv+c2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

SITE_ID = 1

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_seed',


    # Other installed applications
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # Your other apps here



    'whitenoise.runserver_nostatic',
    'blog',
    'music',
    'shop',
    'registration',

    'rest_framework', #Подключение DRF
    'shop_api', #Подключение нового приложения API

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'apps.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'apps.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # Используем MySQL-драйвер
        'NAME': os.environ.get('MYSQL_DB_NAME'),  # Имя базы данных.
        'USER': os.environ.get('MYSQL_DB_USER'),  # Пользователь MySQL
        'PASSWORD': os.environ.get('MYSQL_DB_PASSWORD'),  # Пароль пользователя
        'HOST': os.environ.get('MYSQL_DB_HOST', 'localhost'),  # Адрес сервера MySQL
        'PORT': os.environ.get('MYSQL_DB_PORT', '3306'),  # Порт MySQL (стандартный 3306)
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

'''1. Автоматическая регистрация статики:
   Если у вас папка static внутри каждого приложения (например, app1/static/app1, app2/static/app2 и т.д.), 
   Django автоматически соберёт статику из этих папок благодаря опции STATICFILES_FINDERS, 
   которая по умолчанию включает опцию поиска статики по каждому приложению:'''
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'django.contrib.staticfiles.finders.FileSystemFinder',
]

'''2. Дополнительные пути для статики:
   Если нужно указать конкретные пути для статики, 
   вы можете дополнить STATICFILES_DIRS в settings.py:'''
# STATICFILES_DIRS = [
#     BASE_DIR / 'blog/static/',
#     BASE_DIR / 'shop/static/',
#     BASE_DIR / 'music/static/',
#     BASE_DIR / 'registration/static/'
# ]



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




#Регистрация
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'



#Настройка зоны Минск
TIME_ZONE  = os.environ.get('TIME_ZONE')
USE_TZ = os.environ.get('USE_TZ')


#Настройка кэша
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    }
}

#Настройка почтового клиента (Django settings):
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.mail.ru'
EMAIL_PORT = 465
EMAIL_USE_SSL = True


EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')


DEFAULT_FROM_EMAIL = EMAIL_HOST_USER  # Адрес отправителя по умолчанию
SERVER_EMAIL = EMAIL_HOST_USER        # Адрес для служебных сообщений




