"""
Django settings for apps project.
Generated by 'django-admin startproject' using Django 5.2.7.
For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import environ
import os
from pathlib import Path
# import pymysql
# pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['blogshopmusik.onrender.com']
CSRF_TRUSTED_ORIGINS = ['https://blogshopmusik.onrender.com']
ALLOWED_HOSTS += ["127.0.0.1"]
SITE_ID = 1

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_seed',

    # Other installed applications
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # Your other apps here
    'debug_toolbar',
    'whitenoise.runserver_nostatic',

    'blog',
    'music',
    'shop',
    'registration',

    'rest_framework',
    'shop_api',
    'blog_api',

    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_yasg'
]

# CACHE_MIDDLEWARE_SECONDS = 3600

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # # Средства кеширования
    # 'django.middleware.cache.UpdateCacheMiddleware',
    # 'django.middleware.cache.FetchFromCacheMiddleware',

    #  Settings Django Debug Toolbar
    'debug_toolbar.middleware.DebugToolbarMiddleware',

    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'apps.urls'

#  Settings Django Debug Toolbar
INTERNAL_IPS = ['127.0.0.1', '::1']

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'apps.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database MYSQL
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': os.environ.get('MYSQL_DB_NAME'),
#         'USER': os.environ.get('MYSQL_DB_USER'),
#         'PASSWORD': os.environ.get('MYSQL_DB_PASSWORD'),
#
#         'HOST': os.environ.get('MYSQL_DB_HOST', 'localhost'),
#         # 'HOST': os.environ.get('MYSQL_DB_HOST', 'mysql'),
#         'PORT': os.environ.get('MYSQL_DB_PORT', '3306'),
#     }
# }

# Database POSTGRESQL
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ.get('POSTGRESQL_DB_NAME'),
        'USER': os.environ.get('POSTGRESQL_DB_USER'),
        'PASSWORD': os.environ.get('POSTGRESQL_DB_PASSWORD'),

        # 'HOST': os.environ.get('POSTGRESQL_DB_HOST', 'localhost'),
        'HOST': os.environ.get('POSTGRESQL_DB_HOST', 'postgres'),

        'PORT': os.environ.get('POSTGRESQL_DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'ru-RU'
USE_I18N = True

TIME_ZONE  = os.environ.get('TIME_ZONE')
USE_TZ = os.environ.get('USE_TZ')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static_collected/'
# STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / 'static_collected'

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'django.contrib.staticfiles.finders.FileSystemFinder',
]

STATICFILES_DIRS = [
    BASE_DIR / 'static',
    # BASE_DIR / 'blog/static/blog/',
    # BASE_DIR / 'shop/static/shop/',
    # BASE_DIR / 'music/static/music/',
    # BASE_DIR / 'registration/static/registration/'
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#Регистрация
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'



#Настройка кэша MEMCACHED
# CACHES = {
#     'default': {
#         "BACKEND": "django.core.cache.backends.memcached.PyMemcacheCache",
#         "LOCATION": "127.0.0.1:11211",
#     }
# }
#Настройка кэша REDIS
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#         'LOCATION': 'redis://127.0.0.1:6379/1',
#     }
# }
# Настройка кэша DJANGO
# CACHES = {
#     'default': {
#         "BACKEND": "django.core.cache.backends.db.DatabaseCache",
#         "LOCATION": "my_cache_table",
#     }
# }

#Настройка кэша LocMem -  не подходит для Production
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
#     }
# }
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    }
}


#Настройка почтового клиента (Django settings):
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.mail.ru'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER  # Адрес отправителя по умолчанию
SERVER_EMAIL = EMAIL_HOST_USER        # Адрес для служебных сообщений


# #Settings for DRF and JWT  - START
from datetime import timedelta
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # можно оставить SessionAuthentication для веб-страниц, если нужно:
        # 'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',  # по умолчанию защищаем все API
    )
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=10),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,   # если True — при refresh выдается новый refresh
    'BLACKLIST_AFTER_ROTATION': True, # требует token_blacklist app
    'ALGORITHM': 'HS256',
    # опционально укажи SECRET_KEY, по умолчанию используется Django SECRET_KEY
}
# #Settings for DRF and JWT  - FINISH



CSRF_COOKIE_HTTPONLY = False  # разрешаем доступ к токену через JavaScript


# Этот конфиг настраивает Swagger UI так, чтобы он предлагал ввести токен авторизации при тестировании защищённых эндпоинтов API.
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {  # Определяет типы механизмов защиты (авторизация) для API-документации Swagger
        'Bearer': {  # Название схемы авторизации, обычно Bearer токены используются для JWT-токенов
                     # Имя схемы авторизации. Чаще всего используется схема "Bearer Token", когда клиент передает токен в заголовке Authorization с префиксом "Bearer ".
            'type': 'apiKey',  # Тип механизма авторизации — ключ API
                               # Это означает, что механизм авторизации основан на передаче ключа API (токена) в запросе. Вместо OAuth или других схем используется простой токен.
            'name': 'Authorization',  # Имя заголовка HTTP, содержащего токен авторизации
                                      # Имя заголовка HTTP, в котором указывается токен авторизации. Это стандартный заголовок для передачи токенов Bearer.
            'in': 'header'  # Место расположения ключа авторизации — заголовок HTTP-запроса
                            # Токен помещается в заголовок HTTP-запроса. Альтернативные варианты включают cookie или body (для POST-запросов), но чаще всего используется header.
        }
    },
}


#Settings Celery - включение Celery в настройки Django
# CELERY_BROKER_URL = 'redis://redis:6379/0' # Адрес сервера Redis, используемого в качестве брокера сообщений
# CELERY_RESULT_BACKEND = 'redis://redis:6379/0' # Сервер Redis, хранящий результаты выполненных задач

REDIS_URL = os.getenv('REDIS_URL')
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL

# CELERY_BROKER_URL = os.getenv('REDIS_URL')  # Подключение к Redis через переменную среды
# CELERY_RESULT_BACKEND = os.getenv('REDIS_URL')  # Хранение результатов в Redis

# CELERY_BROKER_URL = 'redis://localhost:6379/0' # Адрес сервера Redis, используемого в качестве брокера сообщений
# CELERY_RESULT_BACKEND = 'redis://localhost:6379/0' # Сервер Redis, хранящий результаты выполненных задач

#CELERY_ACCEPT_CONTENT = ['json'] # Форматы данных, принимаемые брокером (используется JSON)
CELERY_ACCEPT_CONTENT = ['application/json'] # защищает ваше приложение от риска, связанного с небезопасными форматами сериализации, и способствует повышению общей стабильности и производительности
CELERY_TASK_SERIALIZER = 'json' # Формат сериализации результатов выполнения задач (JSON)
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Europe/Minsk'  # Временная зона Минска - Часовой пояс для планирования задач (Минск)

CELERY_WORKER_CONCURRENCY = 4

CELERY_MAX_MEMORY_PER_CHILD = 128

#  Обработчики ошибок
HANDLER404 = 'shop.views.handler404'
HANDLER500 = 'shop.views.handler500'
